version: '3.9'
services:
  url-shortener:
    container_name: shortener
    build: .
    environment:
      - REDIS_URL=redis:6379
      - PROD=1
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: "redis"
    ports:
      - "6379:6379"
